version: '3'
services: 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=edfrancys.victor@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=10041992Ed     
    networks:
      postgres-net: 

networks:
  postgres-net: