version: '3'
services:
  db-postgres: 
    container_name: db-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=adminedfrancys
      - POSTGRES_DB=defaultadmin
      - POSTGRES_PASSWORD=152463Ed
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    networks:
      postgres-net:  

networks:
  postgres-net: